server:
  port: 9090

spring:
  application:
    name: config-server
  cloud:
    config:
      enabled: false
      server:
        git:
          uri: https://github.com/leximus7/spring-cloud-config
          searchPaths: employee
          validate_certificates: false
#          proxy:
#            https:
#              host:
#              password:
#              port: '8080'
#              username:
#  profiles:
#    active: native